language: java
sudo: required
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script: 
- nohup bash -c "cd data/hsqldb/bin && ./runServer.sh &"
- "mvn test"
